package installer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/gstark/agent-manager/internal/db"
)

// ClaudeAdapter installs artifacts for Claude Code.
type ClaudeAdapter struct{}

func (ClaudeAdapter) Name() string { return "claude" }
func (ClaudeAdapter) Install(projectDir string, r *ArtifactSet) ([]ItemResult, error) {
	var results []ItemResult

	// Write .claude/rules/*.md
	rulesDir := filepath.Join(projectDir, ".claude", "rules")
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return nil, err
	}

	for _, rule := range r.Rules {
		changed, err := writeClaudeRule(rulesDir, rule)
		if err != nil {
			return nil, err
		}
		status := StatusUpToDate
		if changed {
			status = StatusInstalled
		}
		results = append(results, ItemResult{Kind: "rule", Name: rule.Name, Status: status})
	}

	for _, lr := range r.LocalRules {
		rule := &db.Rule{
			Name:        lr.Name,
			Description: lr.Description,
			Paths:       lr.Paths,
			Body:        lr.Content,
		}
		changed, err := writeClaudeRule(rulesDir, rule)
		if err != nil {
			return nil, err
		}
		status := StatusUpToDate
		if changed {
			status = StatusInstalled
		}
		results = append(results, ItemResult{Kind: "rule", Name: rule.Name, Status: status})
	}

	// Remove stale .claude/rules/*.md files
	wantedRules := make(map[string]bool, len(r.Rules)+len(r.LocalRules))
	for _, rule := range r.Rules {
		wantedRules[rule.Name] = true
	}
	for _, lr := range r.LocalRules {
		wantedRules[lr.Name] = true
	}
	if err := removeStaleFiles(rulesDir, wantedRules, ".md"); err != nil {
		return nil, err
	}

	// Project skills from canonical .agm/skills/ into .claude/skills/
	if err := projectSkills(projectDir, ".claude", r.Skills); err != nil {
		return nil, err
	}

	// Generate CLAUDE.md as a wrapper that imports AGENTS.md
	claudeContent := "# Project Agent Instructions\n\n<!-- Generated by agm. Do not edit manually. -->\n\n@AGENTS.md\n"
	claudePath := filepath.Join(projectDir, "CLAUDE.md")
	os.Remove(claudePath) // remove existing file/symlink
	if err := os.WriteFile(claudePath, []byte(claudeContent), 0644); err != nil {
		return nil, err
	}

	return results, nil
}

func writeClaudeRule(dir string, rule *db.Rule) (changed bool, err error) {
	var b strings.Builder
	b.WriteString("---\n")
	if len(rule.Paths) > 0 {
		b.WriteString("paths:\n")
		for _, p := range rule.Paths {
			fmt.Fprintf(&b, "  - %q\n", p)
		}
	}
	b.WriteString("---\n\n")
	if rule.Description != "" {
		fmt.Fprintf(&b, "# %s\n\n", rule.Description)
	}
	b.WriteString(strings.TrimSpace(rule.Body))
	b.WriteString("\n")

	return writeFileIfChanged(filepath.Join(dir, rule.Name+".md"), []byte(b.String()))
}
