package installer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func installCodex(projectDir string, r *resolved) error {
	// Generate AGENTS.md from all rules
	var b strings.Builder
	b.WriteString("# Project Agent Instructions\n\n")
	b.WriteString("<!-- Generated by agm. Do not edit manually. -->\n\n")

	for _, rule := range r.rules {
		if len(rule.Paths) > 0 {
			patterns := strings.Join(rule.Paths, ", ")
			fmt.Fprintf(&b, "## %s (applies to: %s)\n\n", rule.Description, patterns)
		} else if rule.Description != "" {
			fmt.Fprintf(&b, "## %s\n\n", rule.Description)
		}
		b.WriteString(strings.TrimSpace(rule.Body))
		b.WriteString("\n\n")
	}

	for _, lr := range r.localRules {
		if len(lr.Paths) > 0 {
			patterns := strings.Join(lr.Paths, ", ")
			fmt.Fprintf(&b, "## %s (applies to: %s)\n\n", lr.Description, patterns)
		} else if lr.Description != "" {
			fmt.Fprintf(&b, "## %s\n\n", lr.Description)
		}
		b.WriteString(strings.TrimSpace(lr.Content))
		b.WriteString("\n\n")
	}

	agentsPath := filepath.Join(projectDir, "AGENTS.md")
	if err := os.WriteFile(agentsPath, []byte(b.String()), 0644); err != nil {
		return err
	}

	// Project skills from canonical .agm/skills/ into .agents/skills/
	return projectSkills(projectDir, ".agents", r.skills)
}
