package installer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// CodexAdapter installs artifacts for Codex.
type CodexAdapter struct{}

func (CodexAdapter) Name() string { return "codex" }
func (CodexAdapter) Install(projectDir string, r *ArtifactSet) ([]ItemResult, error) {
	// Generate AGENTS.md from all rules
	var b strings.Builder
	b.WriteString("# Project Agent Instructions\n\n")
	b.WriteString("<!-- Generated by agm. Do not edit manually. -->\n\n")

	for _, rule := range r.Rules {
		if len(rule.Paths) > 0 {
			patterns := strings.Join(rule.Paths, ", ")
			fmt.Fprintf(&b, "## %s (applies to: %s)\n\n", rule.Description, patterns)
		} else if rule.Description != "" {
			fmt.Fprintf(&b, "## %s\n\n", rule.Description)
		}
		b.WriteString(strings.TrimSpace(rule.Body))
		b.WriteString("\n\n")
	}

	for _, lr := range r.LocalRules {
		if len(lr.Paths) > 0 {
			patterns := strings.Join(lr.Paths, ", ")
			fmt.Fprintf(&b, "## %s (applies to: %s)\n\n", lr.Description, patterns)
		} else if lr.Description != "" {
			fmt.Fprintf(&b, "## %s\n\n", lr.Description)
		}
		b.WriteString(strings.TrimSpace(lr.Content))
		b.WriteString("\n\n")
	}

	agentsPath := filepath.Join(projectDir, "AGENTS.md")
	if err := os.WriteFile(agentsPath, []byte(b.String()), 0644); err != nil {
		return nil, err
	}

	// Project skills from canonical .agm/skills/ into .agents/skills/
	if err := projectSkills(projectDir, ".agents", r.Skills); err != nil {
		return nil, err
	}

	// Write .codex/rules/<name>.md for execution policies
	if len(r.Policies) > 0 {
		codexRulesDir := filepath.Join(projectDir, ".codex", "rules")
		if err := os.MkdirAll(codexRulesDir, 0755); err != nil {
			return nil, err
		}
		for _, p := range r.Policies {
			var pb strings.Builder
			if p.Description != "" {
				fmt.Fprintf(&pb, "# %s\n\n", p.Description)
			}
			pb.WriteString(strings.TrimSpace(p.Body))
			pb.WriteString("\n")
			path := filepath.Join(codexRulesDir, p.Name+".md")
			if err := os.WriteFile(path, []byte(pb.String()), 0644); err != nil {
				return nil, err
			}
		}
	}

	return nil, nil
}
